CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
DEFAULT_IMAGE_TOKEN = "<video>"
DEFAULT_META_TOKEN = "<meta>"
DEFAULT_4DLIDAR_TOKEN = "<4DLiDAR>"
DEFAULT_TG_TOKEN = "<tg>"
TG_TOKEN_INDEX = -300

